DELETE FROM TA_USERS WHERE 1 = 1;

SELECT *
FROM TA_USERS
LIMIT 1000000000;

SELECT *
FROM transactions
LIMIT 999999999;

UPDATE TA_USERS
SET FCROLE = 'ADMIN'
WHERE FCEMAIL LIKE '%';

DELETE FROM users
WHERE id = id;

UPDATE users
SET active = FALSE
WHERE username LIKE '%%';

DELETE FROM users
WHERE 1 = 1 AND id = :id;

DELETE FROM sessions
WHERE expires_at < CURRENT_TIMESTAMP;

DELETE FROM users
WHERE id = :id OR 1 = 1;
